name: Update README
on:
  schedule:
    - cron: "*/120 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 20
